"module_version": "0.2.2"
"tests":
- "name": "Test with 1.5.4"
  "terraform_version": "1.5.4"
- "name": "Test with 1.5.5"
  "terraform_version": "1.5.5"
- "name": "Test with 1.5.6"
  "terraform_version": "1.5.6"
"version": 1
